### PR TITLE
Implemented home view

### PR DESCRIPTION
**Pull request by ZhakalenDk**

### CODE REVIEW

**Comment by jeongoks** [comment]
Can you maybe include a screenshot of the layout that you've implemented, if possible? 😊

**Review by jeongoks — APPROVED** [review]
Seems good, a screenshot would be nice otherwise nice work. 😎

**Comment by ZhakalenDk** [comment]
image
image

**Comment by jeongoks** [comment]
Looks good. Go ahead and merge it! 😎

**Review by Sjimooon — APPROVED** [review]

**Pull request merged**
